### ISSUE TITLE
Making models public not working

### ISSUE THREAD

**Issue by tiku01** [tiku01/oryx-editor#524]
When trying to make a model available for the public in the repository (by pressing the little symbol beside the text "Not Public" within the Access Rights) I get a "Server Communication failed". In the log I see:
````
02-Feb-2015 13:26:32 org.hibernate.util.JDBCExceptionReporter logExceptions
WARNING: SQL Error: 0, SQLState: 42702
02-Feb-2015 13:26:32 org.hibernate.util.JDBCExceptionReporter logExceptions
SEVERE: ERROR: column reference "hierarchy" is ambiguous
  Detail: It could refer to either a PL/pgSQL variable or a table column.
org.hibernate.exception.SQLGrammarException: could not insert: [org.b3mn.poem.In
teraction]
        at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.j
ava:67)
        at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelp
er.java:43)
        at org.hibernate.id.insert.AbstractSelectingDelegate.performInsert(AbstractSelectingDelegate.java:40)
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2108)
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2588)
        at org.hibernate.action.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:48)
        at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:248)
[...]
````
After this error occurs, the server cannot be used anymore without a restart. Any access to the repository or the editor leads to a NullPointerException as follows:
````
02-Feb-2015 13:48:43 org.hibernate.util.JDBCExceptionReporter logExceptions
WARNING: SQL Error: 0, SQLState: 25P02
02-Feb-2015 13:48:43 org.hibernate.util.JDBCExceptionReporter logExceptions
SEVERE: ERROR: current transaction is aborted, commands ignored until end of transaction block
java.lang.NullPointerException
        at org.b3mn.poem.Dispatcher.dispatch(Unknown Source)
        at org.b3mn.poem.Dispatcher.doGet(Unknown Source)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
[...]
````
This is probably caused by changes in PostgresQL made between version 8.3 (originally used by Oryx) and 9.x (used now). The particularies are described at https://wiki.postgresql.org/wiki/What%27s_new_in_PostgreSQL_9.0 at the bottom. It seems we need to adjust how Oryx tries to access the table "hierarchy". The page above mentioned it is possible to revert to the old behaviour, but fixing seems preferable to switching to an old state ...

**Comment by gautamsawala** [comment]
The column name in database and variable name were both "hierarchy", this was causing ambiguity when migragted to postgresql9.x.

Changed the variable name to "hierarchy_text".

Fixed with #516 
While also changed the db_schema for the new installations #530
